/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_uceva_libovaweb_javaLib_OvaWeb */

#ifndef _Included_co_uceva_libovaweb_javaLib_OvaWeb
#define _Included_co_uceva_libovaweb_javaLib_OvaWeb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_uceva_libovaweb_javaLib_OvaWeb
 * Method:    ejecutarComandosGit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_co_uceva_libovaweb_javaLib_OvaWeb_ejecutarComandosGit
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
